### ISSUE TITLE
Error in downloading image from container registry

### ISSUE THREAD

**Issue by lccambiaghi** [tecosaur/org-knit-action#1]
Hi, thank you for this Github Action!! Sounds really useful, exactly what I would need to automatically export to HTML my org files on push.

I set up a [minimal example](https://github.com/lccambiaghi/nixpkgs/blob/main/.github/workflows/export.yml) but the action fails with this error:
```
Download action repository 'tecosaur/org-knit-action@v0.2'
29
Error: 'ghcr.io/tecosaur/org-knit-action:v0.2' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```

Am I doing something wrong? Thanks!!

**Comment by tecosaur** [comment]
This sounds me-related :sweat_smile:, specifically with this line
https://github.com/tecosaur/org-knit-action/blob/abdd2763826ed868ca9323ae7411d1192be01a3a/action.yml#L46

I guess I need to prefix `docker://`? I'll try that in a bit.

**Comment by tecosaur** [comment]
Give `v0.3` a go :)
